id: AA7E0DAF0
title: Prayer to Rendawa Shönnu Lodrö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:20:43.226098
  last_modified_at: 2022-03-01 01:20:43.226110
